In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("../data/raw/dataset_Google-Maps-Reviews-Scraper_Pantai.csv")
df.head()

,title,url,stars,name,reviewUrl,text
0,Pantai Tanjung Gelam,https://www.google.com/maps/search/?api=1&quer...,5,araso mu,https://www.google.com/maps/reviews/data=!4m8!...,NaN
1,Pantai Tanjung Gelam,https://www.google.com/maps/search/?api=1&quer...,5,ARIAN BAWANA,https://www.google.com/maps/reviews/data=!4m8!...,NaN
2,Pantai Tanjung Gelam,https://www.google.com/maps/search/?api=1&quer...,5,Desis Triyasih,https://www.google.com/maps/reviews/data=!4m8!...,Pantai yang menakjubkan dengan pasir-pasir put...
3,Pantai Tanjung Gelam,https://www.google.com/maps/search/?api=1&quer...,5,rizal taufik,https://www.google.com/maps/reviews/data=!4m8!...,Pantai Tanjung Gelam merupakan salah satu pant...
4,Pantai Tanjung Gelam,https://www.google.com/maps/search/?api=1&quer...,5,Iwan Kristianto,https://www.google.com/maps/reviews/data=!4m8!...,"Salah satu pantai favorit bila ke Karimunjawa,..."

In [3]:
df = df[['title', 'stars', 'text']]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   1082 non-null   object
 1   stars   1082 non-null   int64
 2   text    731 non-null    object
dtypes: int64(1), object(2)
memory usage: 25.5+ KB

In [5]:
df['text'] = df['text'].astype(str).str.lower()
df['text'] = df['text'].replace('false', pd.NA)
df = df.dropna(subset=['text'])
df = df[df['text'] != 'false']

In [6]:
df = df.drop_duplicates(subset=['text'])

In [7]:
df = df.dropna()

In [8]:
def clean_gmaps_text(text):
    text = re.sub(r"@[A-Za-z0-9]+", '', text)
    text = re.sub(r"#\w+", '', text)
    text = re.sub(r"RT[\s]+", '', text)
    text = re.sub(r"https?://\S+", '', text)
    text = re.sub(r"[^A-Za-z0-9 ]", '', text)
    text = re.sub(r"\s+", ' ', text).strip()

    return text

df['text'] = df['text'].apply(clean_gmaps_text)

In [9]:
df.head()

,title,stars,text
0,Pantai Tanjung Gelam,5,nan
2,Pantai Tanjung Gelam,5,pantai yang menakjubkan dengan pasirpasir puti...
3,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...
4,Pantai Tanjung Gelam,5,salah satu pantai favorit bila ke karimunjawa ...
5,Pantai Tanjung Gelam,5,pantai denganpasir putih yang bersih panorama ...

In [10]:
df.to_csv('../data/cleaning/clear_data.csv', index=False)